export const AT_HOME_ACTIONTYPES = 'AT_HOME_ACTIONTYPES';
export const AT_MALL_ACTIONTYPES = 'AT_MALL_ACTIONTYPES';
export const AT_PURCHASE_ACTIONTYPES = 'AT_PURCHASE_ACTIONTYPES';
export const AT_PEOPLE_ACTIONTYPES = 'AT_PEOPLE_ACTIONTYPES';